package imgui

// #cgo CFLAGS: -DCIMGUI_DEFINE_ENUMS_AND_STRUCTS=1 -Idist/include
// #include "cimgui/cimgui.h"
import "C"

type BitArrayForNamedKeys C.ImBitArrayForNamedKeys
type BitArrayPtr C.ImBitArrayPtr
type BitVector C.ImBitVector
type Color C.ImColor
type DrawCallback C.ImDrawCallback
type DrawChannel C.ImDrawChannel
type DrawCmd C.ImDrawCmd
type DrawCmdHeader C.ImDrawCmdHeader
type DrawData C.ImDrawData
type DrawDataBuilder C.ImDrawDataBuilder
type DrawFlags C.ImDrawFlags
type DrawIdx C.ImDrawIdx
type DrawList C.ImDrawList
type DrawListFlags C.ImDrawListFlags
type DrawListSharedData C.ImDrawListSharedData
type DrawListSplitter C.ImDrawListSplitter
type DrawVert C.ImDrawVert
type FileHandle C.ImFileHandle
type Font C.ImFont
type FontAtlas C.ImFontAtlas
type FontAtlasCustomRect C.ImFontAtlasCustomRect
type FontAtlasFlags C.ImFontAtlasFlags
type FontBuilderIO C.ImFontBuilderIO
type FontConfig C.ImFontConfig
type FontGlyph C.ImFontGlyph
type FontGlyphRangesBuilder C.ImFontGlyphRangesBuilder
type ActivateFlags C.ImGuiActivateFlags
type BackendFlags C.ImGuiBackendFlags
type BoxSelectState C.ImGuiBoxSelectState
type ButtonFlags C.ImGuiButtonFlags
type ChildFlags C.ImGuiChildFlags
type Col C.ImGuiCol
type ColorEditFlags C.ImGuiColorEditFlags
type ColorMod C.ImGuiColorMod
type ComboFlags C.ImGuiComboFlags
type ComboPreviewData C.ImGuiComboPreviewData
type Cond C.ImGuiCond
type ConfigFlags C.ImGuiConfigFlags
type Context C.ImGuiContext
type ContextHook C.ImGuiContextHook
type ContextHookCallback C.ImGuiContextHookCallback
type DataAuthority C.ImGuiDataAuthority
type DataType C.ImGuiDataType
type DataTypeInfo C.ImGuiDataTypeInfo
type DataTypeStorage C.ImGuiDataTypeStorage
type DataVarInfo C.ImGuiDataVarInfo
type DebugAllocEntry C.ImGuiDebugAllocEntry
type DebugAllocInfo C.ImGuiDebugAllocInfo
type DebugLogFlags C.ImGuiDebugLogFlags
type DockContext C.ImGuiDockContext
type DockNode C.ImGuiDockNode
type DockNodeFlags C.ImGuiDockNodeFlags
type DockNodeSettings C.ImGuiDockNodeSettings
type DockRequest C.ImGuiDockRequest
type DragDropFlags C.ImGuiDragDropFlags
type ErrorCallback C.ImGuiErrorCallback
type ErrorRecoveryState C.ImGuiErrorRecoveryState
type FocusRequestFlags C.ImGuiFocusRequestFlags
type FocusScopeData C.ImGuiFocusScopeData
type FocusedFlags C.ImGuiFocusedFlags
type GroupData C.ImGuiGroupData
type HoveredFlags C.ImGuiHoveredFlags
type ID C.ImGuiID
type IDStackTool C.ImGuiIDStackTool
type IO C.ImGuiIO
type InputEvent C.ImGuiInputEvent
type InputEventAppFocused C.ImGuiInputEventAppFocused
type InputEventKey C.ImGuiInputEventKey
type InputEventMouseButton C.ImGuiInputEventMouseButton
type InputEventMousePos C.ImGuiInputEventMousePos
type InputEventMouseViewport C.ImGuiInputEventMouseViewport
type InputEventMouseWheel C.ImGuiInputEventMouseWheel
type InputEventText C.ImGuiInputEventText
type InputFlags C.ImGuiInputFlags
type InputTextCallback C.ImGuiInputTextCallback
type InputTextCallbackData C.ImGuiInputTextCallbackData
type InputTextDeactivateData C.ImGuiInputTextDeactivateData
type InputTextDeactivatedState C.ImGuiInputTextDeactivatedState
type InputTextFlags C.ImGuiInputTextFlags
type InputTextState C.ImGuiInputTextState
type ItemFlags C.ImGuiItemFlags
type ItemStatusFlags C.ImGuiItemStatusFlags
type KeyChord C.ImGuiKeyChord
type KeyData C.ImGuiKeyData
type KeyOwnerData C.ImGuiKeyOwnerData
type KeyRoutingData C.ImGuiKeyRoutingData
type KeyRoutingIndex C.ImGuiKeyRoutingIndex
type KeyRoutingTable C.ImGuiKeyRoutingTable
type LastItemData C.ImGuiLastItemData
type LayoutType C.ImGuiLayoutType
type ListClipper C.ImGuiListClipper
type ListClipperData C.ImGuiListClipperData
type ListClipperRange C.ImGuiListClipperRange
type LocEntry C.ImGuiLocEntry
type MemAllocFunc C.ImGuiMemAllocFunc
type MemFreeFunc C.ImGuiMemFreeFunc
type MenuColumns C.ImGuiMenuColumns
type MetricsConfig C.ImGuiMetricsConfig
type MouseButton C.ImGuiMouseButton
type MouseCursor C.ImGuiMouseCursor
type MultiSelectFlags C.ImGuiMultiSelectFlags
type MultiSelectIO C.ImGuiMultiSelectIO
type MultiSelectState C.ImGuiMultiSelectState
type MultiSelectTempData C.ImGuiMultiSelectTempData
type NavHighlightFlags C.ImGuiNavHighlightFlags
type NavItemData C.ImGuiNavItemData
type NavMoveFlags C.ImGuiNavMoveFlags
type NextItemData C.ImGuiNextItemData
type NextItemDataFlags C.ImGuiNextItemDataFlags
type NextWindowData C.ImGuiNextWindowData
type NextWindowDataFlags C.ImGuiNextWindowDataFlags
type OldColumnData C.ImGuiOldColumnData
type OldColumnFlags C.ImGuiOldColumnFlags
type OldColumns C.ImGuiOldColumns
type OnceUponAFrame C.ImGuiOnceUponAFrame
type Payload C.ImGuiPayload
type PlatformIO C.ImGuiPlatformIO
type PlatformImeData C.ImGuiPlatformImeData
type PlatformMonitor C.ImGuiPlatformMonitor
type PopupData C.ImGuiPopupData
type PopupFlags C.ImGuiPopupFlags
type PtrOrIndex C.ImGuiPtrOrIndex
type ScrollFlags C.ImGuiScrollFlags
type SelectableFlags C.ImGuiSelectableFlags
type SelectionBasicStorage C.ImGuiSelectionBasicStorage
type SelectionExternalStorage C.ImGuiSelectionExternalStorage
type SelectionRequest C.ImGuiSelectionRequest
type SelectionUserData C.ImGuiSelectionUserData
type SeparatorFlags C.ImGuiSeparatorFlags
type SettingsHandler C.ImGuiSettingsHandler
type ShrinkWidthItem C.ImGuiShrinkWidthItem
type SizeCallback C.ImGuiSizeCallback
type SizeCallbackData C.ImGuiSizeCallbackData
type SliderFlags C.ImGuiSliderFlags
type StackLevelInfo C.ImGuiStackLevelInfo
type Storage C.ImGuiStorage
type StoragePair C.ImGuiStoragePair
type Style C.ImGuiStyle
type StyleMod C.ImGuiStyleMod
type StyleVar C.ImGuiStyleVar
type TabBar C.ImGuiTabBar
type TabBarFlags C.ImGuiTabBarFlags
type TabItem C.ImGuiTabItem
type TabItemFlags C.ImGuiTabItemFlags
type Table C.ImGuiTable
type TableBgTarget C.ImGuiTableBgTarget
type TableCellData C.ImGuiTableCellData
type TableColumn C.ImGuiTableColumn
type TableColumnFlags C.ImGuiTableColumnFlags
type TableColumnIdx C.ImGuiTableColumnIdx
type TableColumnSettings C.ImGuiTableColumnSettings
type TableColumnSortSpecs C.ImGuiTableColumnSortSpecs
type TableColumnsSettings C.ImGuiTableColumnsSettings
type TableDrawChannelIdx C.ImGuiTableDrawChannelIdx
type TableFlags C.ImGuiTableFlags
type TableHeaderData C.ImGuiTableHeaderData
type TableInstanceData C.ImGuiTableInstanceData
type TableRowFlags C.ImGuiTableRowFlags
type TableSettings C.ImGuiTableSettings
type TableSortSpecs C.ImGuiTableSortSpecs
type TableTempData C.ImGuiTableTempData
type TextBuffer C.ImGuiTextBuffer
type TextFilter C.ImGuiTextFilter
type TextFlags C.ImGuiTextFlags
type TextIndex C.ImGuiTextIndex
type TextRange C.ImGuiTextRange
type TooltipFlags C.ImGuiTooltipFlags
type TreeNodeFlags C.ImGuiTreeNodeFlags
type TreeNodeStackData C.ImGuiTreeNodeStackData
type TypingSelectFlags C.ImGuiTypingSelectFlags
type TypingSelectRequest C.ImGuiTypingSelectRequest
type TypingSelectState C.ImGuiTypingSelectState
type Viewport C.ImGuiViewport
type ViewportFlags C.ImGuiViewportFlags
type ViewportP C.ImGuiViewportP
type Window C.ImGuiWindow
type WindowClass C.ImGuiWindowClass
type WindowDockStyle C.ImGuiWindowDockStyle
type WindowFlags C.ImGuiWindowFlags
type WindowRefreshFlags C.ImGuiWindowRefreshFlags
type WindowSettings C.ImGuiWindowSettings
type WindowStackData C.ImGuiWindowStackData
type WindowTempData C.ImGuiWindowTempData
type PoolIdx C.ImPoolIdx
type Rect C.ImRect
type S16 C.ImS16
type S32 C.ImS32
type S64 C.ImS64
type S8 C.ImS8
type StbTexteditState C.ImStbTexteditState
type TextureID C.ImTextureID
type U16 C.ImU16
type U32 C.ImU32
type U64 C.ImU64
type U8 C.ImU8
type Vec1 C.ImVec1
type Vec2 C.ImVec2
type Vec2ih C.ImVec2ih
type Vec4 C.ImVec4
type Wchar C.ImWchar
type Wchar16 C.ImWchar16
type Wchar32 C.ImWchar32
type STB_TexteditState C.STB_TexteditState
