#include "thirdparty/glfw/src/context.c"
#include "thirdparty/glfw/src/init.c"
#include "thirdparty/glfw/src/input.c"
#include "thirdparty/glfw/src/monitor.c"
#include "thirdparty/glfw/src/vulkan.c"
#include "thirdparty/glfw/src/window.c"
#include "thirdparty/glfw/src/osmesa_context.c"

#include "thirdparty/glfw/src/win32_init.c"
#include "thirdparty/glfw/src/win32_joystick.c"
#include "thirdparty/glfw/src/win32_monitor.c"
#include "thirdparty/glfw/src/win32_time.c"
#include "thirdparty/glfw/src/win32_thread.c"
#include "thirdparty/glfw/src/win32_window.c"
#include "thirdparty/glfw/src/wgl_context.c"
#include "thirdparty/glfw/src/egl_context.c"