package imgui

const WindowFlags_None = 0
const WindowFlags_NoTitleBar = 1 << 0
const WindowFlags_NoResize = 1 << 1
const WindowFlags_NoMove = 1 << 2
const WindowFlags_NoScrollbar = 1 << 3
const WindowFlags_NoScrollWithMouse = 1 << 4
const WindowFlags_NoCollapse = 1 << 5
const WindowFlags_AlwaysAutoResize = 1 << 6
const WindowFlags_NoBackground = 1 << 7
const WindowFlags_NoSavedSettings = 1 << 8
const WindowFlags_NoMouseInputs = 1 << 9
const WindowFlags_MenuBar = 1 << 10
const WindowFlags_HorizontalScrollbar = 1 << 11
const WindowFlags_NoFocusOnAppearing = 1 << 12
const WindowFlags_NoBringToFrontOnFocus = 1 << 13
const WindowFlags_AlwaysVerticalScrollbar = 1 << 14
const WindowFlags_AlwaysHorizontalScrollbar = 1<< 15
const WindowFlags_NoNavInputs = 1 << 16
const WindowFlags_NoNavFocus = 1 << 17
const WindowFlags_UnsavedDocument = 1 << 18
const WindowFlags_NoDocking = 1 << 19
const WindowFlags_NoNav = WindowFlags_NoNavInputs | WindowFlags_NoNavFocus
const WindowFlags_NoDecoration = WindowFlags_NoTitleBar | WindowFlags_NoResize | WindowFlags_NoScrollbar | WindowFlags_NoCollapse
const WindowFlags_NoInputs = WindowFlags_NoMouseInputs | WindowFlags_NoNavInputs | WindowFlags_NoNavFocus
const WindowFlags_ChildWindow = 1 << 24
const WindowFlags_Tooltip = 1 << 25
const WindowFlags_Popup = 1 << 26
const WindowFlags_Modal = 1 << 27
const WindowFlags_ChildMenu = 1 << 28
const WindowFlags_DockNodeHost = 1 << 29
const ChildFlags_None = 0
const ChildFlags_Borders = 1 << 0
const ChildFlags_AlwaysUseWindowPadding = 1 << 1
const ChildFlags_ResizeX = 1 << 2
const ChildFlags_ResizeY = 1 << 3
const ChildFlags_AutoResizeX = 1 << 4
const ChildFlags_AutoResizeY = 1 << 5
const ChildFlags_AlwaysAutoResize = 1 << 6
const ChildFlags_FrameStyle = 1 << 7
const ChildFlags_NavFlattened = 1 << 8
const ItemFlags_None = 0
const ItemFlags_NoTabStop = 1 << 0
const ItemFlags_NoNav = 1 << 1
const ItemFlags_NoNavDefaultFocus = 1 << 2
const ItemFlags_ButtonRepeat = 1 << 3
const ItemFlags_AutoClosePopups = 1 << 4
const ItemFlags_AllowDuplicateId = 1 << 5
const InputTextFlags_None = 0
const InputTextFlags_CharsDecimal = 1 << 0
const InputTextFlags_CharsHexadecimal = 1 << 1
const InputTextFlags_CharsScientific = 1 << 2
const InputTextFlags_CharsUppercase = 1 << 3
const InputTextFlags_CharsNoBlank = 1 << 4
const InputTextFlags_AllowTabInput = 1 << 5
const InputTextFlags_EnterReturnsTrue = 1 << 6
const InputTextFlags_EscapeClearsAll = 1 << 7
const InputTextFlags_CtrlEnterForNewLine = 1 << 8
const InputTextFlags_ReadOnly = 1 << 9
const InputTextFlags_Password = 1 << 10
const InputTextFlags_AlwaysOverwrite = 1 << 11
const InputTextFlags_AutoSelectAll = 1 << 12
const InputTextFlags_ParseEmptyRefVal = 1 << 13
const InputTextFlags_DisplayEmptyRefVal = 1 << 14
const InputTextFlags_NoHorizontalScroll = 1 << 15
const InputTextFlags_NoUndoRedo = 1 << 16
const InputTextFlags_CallbackCompletion = 1 << 17
const InputTextFlags_CallbackHistory = 1 << 18
const InputTextFlags_CallbackAlways = 1 << 19
const InputTextFlags_CallbackCharFilter = 1 << 20
const InputTextFlags_CallbackResize = 1 << 21
const InputTextFlags_CallbackEdit = 1 << 22
const TreeNodeFlags_None = 0
const TreeNodeFlags_Selected = 1 << 0
const TreeNodeFlags_Framed = 1 << 1
const TreeNodeFlags_AllowOverlap = 1 << 2
const TreeNodeFlags_NoTreePushOnOpen = 1 << 3
const TreeNodeFlags_NoAutoOpenOnLog = 1 << 4
const TreeNodeFlags_DefaultOpen = 1 << 5
const TreeNodeFlags_OpenOnDoubleClick = 1 << 6
const TreeNodeFlags_OpenOnArrow = 1 << 7
const TreeNodeFlags_Leaf = 1 << 8
const TreeNodeFlags_Bullet = 1 << 9
const TreeNodeFlags_FramePadding = 1 << 10
const TreeNodeFlags_SpanAvailWidth = 1 << 11
const TreeNodeFlags_SpanFullWidth = 1 << 12
const TreeNodeFlags_SpanTextWidth = 1 << 13
const TreeNodeFlags_SpanAllColumns = 1 << 14
const TreeNodeFlags_NavLeftJumpsBackHere = 1 << 15
const TreeNodeFlags_CollapsingHeader = TreeNodeFlags_Framed | TreeNodeFlags_NoTreePushOnOpen | TreeNodeFlags_NoAutoOpenOnLog
const PopupFlags_None = 0
const PopupFlags_MouseButtonLeft = 0
const PopupFlags_MouseButtonRight = 1
const PopupFlags_MouseButtonMiddle = 2
const PopupFlags_MouseButtonMask_ = 0x1F
const PopupFlags_MouseButtonDefault_ = 1
const PopupFlags_NoReopen = 1 << 5
const PopupFlags_NoOpenOverExistingPopup = 1 << 7
const PopupFlags_NoOpenOverItems = 1 << 8
const PopupFlags_AnyPopupId = 1 << 10
const PopupFlags_AnyPopupLevel = 1 << 11
const PopupFlags_AnyPopup = PopupFlags_AnyPopupId | PopupFlags_AnyPopupLevel
const SelectableFlags_None = 0
const SelectableFlags_NoAutoClosePopups = 1 << 0
const SelectableFlags_SpanAllColumns = 1 << 1
const SelectableFlags_AllowDoubleClick = 1 << 2
const SelectableFlags_Disabled = 1 << 3
const SelectableFlags_AllowOverlap = 1 << 4
const SelectableFlags_Highlight = 1 << 5
const ComboFlags_None = 0
const ComboFlags_PopupAlignLeft = 1 << 0
const ComboFlags_HeightSmall = 1 << 1
const ComboFlags_HeightRegular = 1 << 2
const ComboFlags_HeightLarge = 1 << 3
const ComboFlags_HeightLargest = 1 << 4
const ComboFlags_NoArrowButton = 1 << 5
const ComboFlags_NoPreview = 1 << 6
const ComboFlags_WidthFitPreview = 1 << 7
const ComboFlags_HeightMask_ = ComboFlags_HeightSmall | ComboFlags_HeightRegular | ComboFlags_HeightLarge | ComboFlags_HeightLargest
const TabBarFlags_None = 0
const TabBarFlags_Reorderable = 1 << 0
const TabBarFlags_AutoSelectNewTabs = 1 << 1
const TabBarFlags_TabListPopupButton = 1 << 2
const TabBarFlags_NoCloseWithMiddleMouseButton = 1 << 3
const TabBarFlags_NoTabListScrollingButtons = 1 << 4
const TabBarFlags_NoTooltip = 1 << 5
const TabBarFlags_DrawSelectedOverline = 1 << 6
const TabBarFlags_FittingPolicyResizeDown = 1 << 7
const TabBarFlags_FittingPolicyScroll = 1 << 8
const TabBarFlags_FittingPolicyMask_ = TabBarFlags_FittingPolicyResizeDown | TabBarFlags_FittingPolicyScroll
const TabBarFlags_FittingPolicyDefault_ = TabBarFlags_FittingPolicyResizeDown
const TabItemFlags_None = 0
const TabItemFlags_UnsavedDocument = 1 << 0
const TabItemFlags_SetSelected = 1 << 1
const TabItemFlags_NoCloseWithMiddleMouseButton = 1 << 2
const TabItemFlags_NoPushId = 1 << 3
const TabItemFlags_NoTooltip = 1 << 4
const TabItemFlags_NoReorder = 1 << 5
const TabItemFlags_Leading = 1 << 6
const TabItemFlags_Trailing = 1 << 7
const TabItemFlags_NoAssumedClosure = 1 << 8
const FocusedFlags_None = 0
const FocusedFlags_ChildWindows = 1 << 0
const FocusedFlags_RootWindow = 1 << 1
const FocusedFlags_AnyWindow = 1 << 2
const FocusedFlags_NoPopupHierarchy = 1 << 3
const FocusedFlags_DockHierarchy = 1 << 4
const FocusedFlags_RootAndChildWindows = FocusedFlags_RootWindow | FocusedFlags_ChildWindows
const HoveredFlags_None = 0
const HoveredFlags_ChildWindows = 1 << 0
const HoveredFlags_RootWindow = 1 << 1
const HoveredFlags_AnyWindow = 1 << 2
const HoveredFlags_NoPopupHierarchy = 1 << 3
const HoveredFlags_DockHierarchy = 1 << 4
const HoveredFlags_AllowWhenBlockedByPopup = 1 << 5
const HoveredFlags_AllowWhenBlockedByActiveItem = 1 << 7
const HoveredFlags_AllowWhenOverlappedByItem = 1 << 8
const HoveredFlags_AllowWhenOverlappedByWindow = 1 << 9
const HoveredFlags_AllowWhenDisabled = 1 << 10
const HoveredFlags_NoNavOverride = 1 << 11
const HoveredFlags_AllowWhenOverlapped = HoveredFlags_AllowWhenOverlappedByItem | HoveredFlags_AllowWhenOverlappedByWindow
const HoveredFlags_RectOnly = HoveredFlags_AllowWhenBlockedByPopup | HoveredFlags_AllowWhenBlockedByActiveItem | HoveredFlags_AllowWhenOverlapped
const HoveredFlags_RootAndChildWindows = HoveredFlags_RootWindow | HoveredFlags_ChildWindows
const HoveredFlags_ForTooltip = 1 << 12
const HoveredFlags_Stationary = 1 << 13
const HoveredFlags_DelayNone = 1 << 14
const HoveredFlags_DelayShort = 1 << 15
const HoveredFlags_DelayNormal = 1 << 16
const HoveredFlags_NoSharedDelay = 1 << 17
const DockNodeFlags_None = 0
const DockNodeFlags_KeepAliveOnly = 1 << 0
const DockNodeFlags_NoDockingOverCentralNode = 1 << 2
const DockNodeFlags_PassthruCentralNode = 1 << 3
const DockNodeFlags_NoDockingSplit = 1 << 4
const DockNodeFlags_NoResize = 1 << 5
const DockNodeFlags_AutoHideTabBar = 1 << 6
const DockNodeFlags_NoUndocking = 1 << 7
const DragDropFlags_None = 0
const DragDropFlags_SourceNoPreviewTooltip = 1 << 0
const DragDropFlags_SourceNoDisableHover = 1 << 1
const DragDropFlags_SourceNoHoldToOpenOthers = 1 << 2
const DragDropFlags_SourceAllowNullID = 1 << 3
const DragDropFlags_SourceExtern = 1 << 4
const DragDropFlags_PayloadAutoExpire = 1 << 5
const DragDropFlags_PayloadNoCrossContext = 1 << 6
const DragDropFlags_PayloadNoCrossProcess = 1 << 7
const DragDropFlags_AcceptBeforeDelivery = 1 << 10
const DragDropFlags_AcceptNoDrawDefaultRect = 1 << 11
const DragDropFlags_AcceptNoPreviewTooltip = 1 << 12
const DragDropFlags_AcceptPeekOnly = DragDropFlags_AcceptBeforeDelivery | DragDropFlags_AcceptNoDrawDefaultRect
const DataType_S8 = 0
const DataType_U8 = 1
const DataType_S16 = 2
const DataType_U16 = 3
const DataType_S32 = 4
const DataType_U32 = 5
const DataType_S64 = 6
const DataType_U64 = 7
const DataType_Float = 8
const DataType_Double = 9
const DataType_Bool = 10
const DataType_COUNT = 11
const Dir_None = -1
const Dir_Left = 0
const Dir_Right = 1
const Dir_Up = 2
const Dir_Down = 3
const Dir_COUNT = 4
const SortDirection_None = 0
const SortDirection_Ascending = 1
const SortDirection_Descending = 2
const Key_None = 0
const Key_Tab = 512
const Key_LeftArrow = 513
const Key_RightArrow = 514
const Key_UpArrow = 515
const Key_DownArrow = 516
const Key_PageUp = 517
const Key_PageDown = 518
const Key_Home = 519
const Key_End = 520
const Key_Insert = 521
const Key_Delete = 522
const Key_Backspace = 523
const Key_Space = 524
const Key_Enter = 525
const Key_Escape = 526
const Key_LeftCtrl = 527
const Key_LeftShift = 528
const Key_LeftAlt = 529
const Key_LeftSuper = 530
const Key_RightCtrl = 531
const Key_RightShift = 532
const Key_RightAlt = 533
const Key_RightSuper = 534
const Key_Menu = 535
const Key_0 = 536
const Key_1 = 537
const Key_2 = 538
const Key_3 = 539
const Key_4 = 540
const Key_5 = 541
const Key_6 = 542
const Key_7 = 543
const Key_8 = 544
const Key_9 = 545
const Key_A = 546
const Key_B = 547
const Key_C = 548
const Key_D = 549
const Key_E = 550
const Key_F = 551
const Key_G = 552
const Key_H = 553
const Key_I = 554
const Key_J = 555
const Key_K = 556
const Key_L = 557
const Key_M = 558
const Key_N = 559
const Key_O = 560
const Key_P = 561
const Key_Q = 562
const Key_R = 563
const Key_S = 564
const Key_T = 565
const Key_U = 566
const Key_V = 567
const Key_W = 568
const Key_X = 569
const Key_Y = 570
const Key_Z = 571
const Key_F1 = 572
const Key_F2 = 573
const Key_F3 = 574
const Key_F4 = 575
const Key_F5 = 576
const Key_F6 = 577
const Key_F7 = 578
const Key_F8 = 579
const Key_F9 = 580
const Key_F10 = 581
const Key_F11 = 582
const Key_F12 = 583
const Key_F13 = 584
const Key_F14 = 585
const Key_F15 = 586
const Key_F16 = 587
const Key_F17 = 588
const Key_F18 = 589
const Key_F19 = 590
const Key_F20 = 591
const Key_F21 = 592
const Key_F22 = 593
const Key_F23 = 594
const Key_F24 = 595
const Key_Apostrophe = 596
const Key_Comma = 597
const Key_Minus = 598
const Key_Period = 599
const Key_Slash = 600
const Key_Semicolon = 601
const Key_Equal = 602
const Key_LeftBracket = 603
const Key_Backslash = 604
const Key_RightBracket = 605
const Key_GraveAccent = 606
const Key_CapsLock = 607
const Key_ScrollLock = 608
const Key_NumLock = 609
const Key_PrintScreen = 610
const Key_Pause = 611
const Key_Keypad0 = 612
const Key_Keypad1 = 613
const Key_Keypad2 = 614
const Key_Keypad3 = 615
const Key_Keypad4 = 616
const Key_Keypad5 = 617
const Key_Keypad6 = 618
const Key_Keypad7 = 619
const Key_Keypad8 = 620
const Key_Keypad9 = 621
const Key_KeypadDecimal = 622
const Key_KeypadDivide = 623
const Key_KeypadMultiply = 624
const Key_KeypadSubtract = 625
const Key_KeypadAdd = 626
const Key_KeypadEnter = 627
const Key_KeypadEqual = 628
const Key_AppBack = 629
const Key_AppForward = 630
const Key_GamepadStart = 631
const Key_GamepadBack = 632
const Key_GamepadFaceLeft = 633
const Key_GamepadFaceRight = 634
const Key_GamepadFaceUp = 635
const Key_GamepadFaceDown = 636
const Key_GamepadDpadLeft = 637
const Key_GamepadDpadRight = 638
const Key_GamepadDpadUp = 639
const Key_GamepadDpadDown = 640
const Key_GamepadL1 = 641
const Key_GamepadR1 = 642
const Key_GamepadL2 = 643
const Key_GamepadR2 = 644
const Key_GamepadL3 = 645
const Key_GamepadR3 = 646
const Key_GamepadLStickLeft = 647
const Key_GamepadLStickRight = 648
const Key_GamepadLStickUp = 649
const Key_GamepadLStickDown = 650
const Key_GamepadRStickLeft = 651
const Key_GamepadRStickRight = 652
const Key_GamepadRStickUp = 653
const Key_GamepadRStickDown = 654
const Key_MouseLeft = 655
const Key_MouseRight = 656
const Key_MouseMiddle = 657
const Key_MouseX1 = 658
const Key_MouseX2 = 659
const Key_MouseWheelX = 660
const Key_MouseWheelY = 661
const Key_ReservedForModCtrl = 662
const Key_ReservedForModShift = 663
const Key_ReservedForModAlt = 664
const Key_ReservedForModSuper = 665
const Key_COUNT = 666
const Mod_None = 0
const Mod_Ctrl = 1 << 12
const Mod_Shift = 1 << 13
const Mod_Alt = 1 << 14
const Mod_Super = 1 << 15
const Mod_Mask_ = 0xF000
const Key_NamedKey_BEGIN = 512
const Key_NamedKey_END = Key_COUNT
const Key_NamedKey_COUNT = Key_NamedKey_END - Key_NamedKey_BEGIN
const Key_KeysData_SIZE = Key_NamedKey_COUNT
const Key_KeysData_OFFSET = Key_NamedKey_BEGIN
const InputFlags_None = 0
const InputFlags_Repeat = 1 << 0
const InputFlags_RouteActive = 1 << 10
const InputFlags_RouteFocused = 1 << 11
const InputFlags_RouteGlobal = 1 << 12
const InputFlags_RouteAlways = 1 << 13
const InputFlags_RouteOverFocused = 1 << 14
const InputFlags_RouteOverActive = 1 << 15
const InputFlags_RouteUnlessBgFocused = 1 << 16
const InputFlags_RouteFromRootWindow = 1 << 17
const InputFlags_Tooltip = 1 << 18
const ConfigFlags_None = 0
const ConfigFlags_NavEnableKeyboard = 1 << 0
const ConfigFlags_NavEnableGamepad = 1 << 1
const ConfigFlags_NavEnableSetMousePos = 1 << 2
const ConfigFlags_NavNoCaptureKeyboard = 1 << 3
const ConfigFlags_NoMouse = 1 << 4
const ConfigFlags_NoMouseCursorChange = 1 << 5
const ConfigFlags_NoKeyboard = 1 << 6
const ConfigFlags_DockingEnable = 1 << 7
const ConfigFlags_ViewportsEnable = 1 << 10
const ConfigFlags_DpiEnableScaleViewports = 1 << 14
const ConfigFlags_DpiEnableScaleFonts = 1 << 15
const ConfigFlags_IsSRGB = 1 << 20
const ConfigFlags_IsTouchScreen = 1 << 21
const BackendFlags_None = 0
const BackendFlags_HasGamepad = 1 << 0
const BackendFlags_HasMouseCursors = 1 << 1
const BackendFlags_HasSetMousePos = 1 << 2
const BackendFlags_RendererHasVtxOffset = 1 << 3
const BackendFlags_PlatformHasViewports = 1 << 10
const BackendFlags_HasMouseHoveredViewport = 1 << 11
const BackendFlags_RendererHasViewports = 1 << 12
const Col_Text = 0
const Col_TextDisabled = 1
const Col_WindowBg = 2
const Col_ChildBg = 3
const Col_PopupBg = 4
const Col_Border = 5
const Col_BorderShadow = 6
const Col_FrameBg = 7
const Col_FrameBgHovered = 8
const Col_FrameBgActive = 9
const Col_TitleBg = 10
const Col_TitleBgActive = 11
const Col_TitleBgCollapsed = 12
const Col_MenuBarBg = 13
const Col_ScrollbarBg = 14
const Col_ScrollbarGrab = 15
const Col_ScrollbarGrabHovered = 16
const Col_ScrollbarGrabActive = 17
const Col_CheckMark = 18
const Col_SliderGrab = 19
const Col_SliderGrabActive = 20
const Col_Button = 21
const Col_ButtonHovered = 22
const Col_ButtonActive = 23
const Col_Header = 24
const Col_HeaderHovered = 25
const Col_HeaderActive = 26
const Col_Separator = 27
const Col_SeparatorHovered = 28
const Col_SeparatorActive = 29
const Col_ResizeGrip = 30
const Col_ResizeGripHovered = 31
const Col_ResizeGripActive = 32
const Col_TabHovered = 33
const Col_Tab = 34
const Col_TabSelected = 35
const Col_TabSelectedOverline = 36
const Col_TabDimmed = 37
const Col_TabDimmedSelected = 38
const Col_TabDimmedSelectedOverline = 39
const Col_DockingPreview = 40
const Col_DockingEmptyBg = 41
const Col_PlotLines = 42
const Col_PlotLinesHovered = 43
const Col_PlotHistogram = 44
const Col_PlotHistogramHovered = 45
const Col_TableHeaderBg = 46
const Col_TableBorderStrong = 47
const Col_TableBorderLight = 48
const Col_TableRowBg = 49
const Col_TableRowBgAlt = 50
const Col_TextLink = 51
const Col_TextSelectedBg = 52
const Col_DragDropTarget = 53
const Col_NavHighlight = 54
const Col_NavWindowingHighlight = 55
const Col_NavWindowingDimBg = 56
const Col_ModalWindowDimBg = 57
const Col_COUNT = 58
const StyleVar_Alpha = 0
const StyleVar_DisabledAlpha = 1
const StyleVar_WindowPadding = 2
const StyleVar_WindowRounding = 3
const StyleVar_WindowBorderSize = 4
const StyleVar_WindowMinSize = 5
const StyleVar_WindowTitleAlign = 6
const StyleVar_ChildRounding = 7
const StyleVar_ChildBorderSize = 8
const StyleVar_PopupRounding = 9
const StyleVar_PopupBorderSize = 10
const StyleVar_FramePadding = 11
const StyleVar_FrameRounding = 12
const StyleVar_FrameBorderSize = 13
const StyleVar_ItemSpacing = 14
const StyleVar_ItemInnerSpacing = 15
const StyleVar_IndentSpacing = 16
const StyleVar_CellPadding = 17
const StyleVar_ScrollbarSize = 18
const StyleVar_ScrollbarRounding = 19
const StyleVar_GrabMinSize = 20
const StyleVar_GrabRounding = 21
const StyleVar_TabRounding = 22
const StyleVar_TabBorderSize = 23
const StyleVar_TabBarBorderSize = 24
const StyleVar_TabBarOverlineSize = 25
const StyleVar_TableAngledHeadersAngle = 26
const StyleVar_TableAngledHeadersTextAlign = 27
const StyleVar_ButtonTextAlign = 28
const StyleVar_SelectableTextAlign = 29
const StyleVar_SeparatorTextBorderSize = 30
const StyleVar_SeparatorTextAlign = 31
const StyleVar_SeparatorTextPadding = 32
const StyleVar_DockingSeparatorSize = 33
const StyleVar_COUNT = 34
const ButtonFlags_None = 0
const ButtonFlags_MouseButtonLeft = 1 << 0
const ButtonFlags_MouseButtonRight = 1 << 1
const ButtonFlags_MouseButtonMiddle = 1 << 2
const ButtonFlags_MouseButtonMask_ = ButtonFlags_MouseButtonLeft | ButtonFlags_MouseButtonRight | ButtonFlags_MouseButtonMiddle
const ColorEditFlags_None = 0
const ColorEditFlags_NoAlpha = 1 << 1
const ColorEditFlags_NoPicker = 1 << 2
const ColorEditFlags_NoOptions = 1 << 3
const ColorEditFlags_NoSmallPreview = 1 << 4
const ColorEditFlags_NoInputs = 1 << 5
const ColorEditFlags_NoTooltip = 1 << 6
const ColorEditFlags_NoLabel = 1 << 7
const ColorEditFlags_NoSidePreview = 1 << 8
const ColorEditFlags_NoDragDrop = 1 << 9
const ColorEditFlags_NoBorder = 1 << 10
const ColorEditFlags_AlphaBar = 1 << 16
const ColorEditFlags_AlphaPreview = 1 << 17
const ColorEditFlags_AlphaPreviewHalf = 1 << 18
const ColorEditFlags_HDR = 1 << 19
const ColorEditFlags_DisplayRGB = 1 << 20
const ColorEditFlags_DisplayHSV = 1 << 21
const ColorEditFlags_DisplayHex = 1 << 22
const ColorEditFlags_Uint8 = 1 << 23
const ColorEditFlags_Float = 1 << 24
const ColorEditFlags_PickerHueBar = 1 << 25
const ColorEditFlags_PickerHueWheel = 1 << 26
const ColorEditFlags_InputRGB = 1 << 27
const ColorEditFlags_InputHSV = 1 << 28
const ColorEditFlags_DefaultOptions_ = ColorEditFlags_Uint8 | ColorEditFlags_DisplayRGB | ColorEditFlags_InputRGB | ColorEditFlags_PickerHueBar
const ColorEditFlags_DisplayMask_ = ColorEditFlags_DisplayRGB | ColorEditFlags_DisplayHSV | ColorEditFlags_DisplayHex
const ColorEditFlags_DataTypeMask_ = ColorEditFlags_Uint8 | ColorEditFlags_Float
const ColorEditFlags_PickerMask_ = ColorEditFlags_PickerHueWheel | ColorEditFlags_PickerHueBar
const ColorEditFlags_InputMask_ = ColorEditFlags_InputRGB | ColorEditFlags_InputHSV
const SliderFlags_None = 0
const SliderFlags_AlwaysClamp = 1 << 4
const SliderFlags_Logarithmic = 1 << 5
const SliderFlags_NoRoundToFormat = 1 << 6
const SliderFlags_NoInput = 1 << 7
const SliderFlags_WrapAround = 1 << 8
const SliderFlags_InvalidMask_ = 0x7000000F
const MouseButton_Left = 0
const MouseButton_Right = 1
const MouseButton_Middle = 2
const MouseButton_COUNT = 5
const MouseCursor_None = -1
const MouseCursor_Arrow = 0
const MouseCursor_TextInput = 0
const MouseCursor_ResizeAll = 1
const MouseCursor_ResizeNS = 2
const MouseCursor_ResizeEW = 3
const MouseCursor_ResizeNESW = 4
const MouseCursor_ResizeNWSE = 5
const MouseCursor_Hand = 6
const MouseCursor_NotAllowed = 7
const MouseCursor_COUNT = 8
const MouseSource_Mouse = 0
const MouseSource_TouchScreen = 1
const MouseSource_Pen = 2
const MouseSource_COUNT = 3
const Cond_None = 0
const Cond_Always = 1 << 0
const Cond_Once = 1 << 1
const Cond_FirstUseEver = 1 << 2
const Cond_Appearing = 1 << 3
const TableFlags_None = 0
const TableFlags_Resizable = 1 << 0
const TableFlags_Reorderable = 1 << 1
const TableFlags_Hideable = 1 << 2
const TableFlags_Sortable = 1 << 3
const TableFlags_NoSavedSettings = 1 << 4
const TableFlags_ContextMenuInBody = 1 << 5
const TableFlags_RowBg = 1 << 6
const TableFlags_BordersInnerH = 1 << 7
const TableFlags_BordersOuterH = 1 << 8
const TableFlags_BordersInnerV = 1 << 9
const TableFlags_BordersOuterV = 1 << 10
const TableFlags_BordersH = TableFlags_BordersInnerH | TableFlags_BordersOuterH
const TableFlags_BordersV = TableFlags_BordersInnerV | TableFlags_BordersOuterV
const TableFlags_BordersInner = TableFlags_BordersInnerV | TableFlags_BordersInnerH
const TableFlags_BordersOuter = TableFlags_BordersOuterV | TableFlags_BordersOuterH
const TableFlags_Borders = TableFlags_BordersInner | TableFlags_BordersOuter
const TableFlags_NoBordersInBody = 1 << 11
const TableFlags_NoBordersInBodyUntilResize = 1 << 12
const TableFlags_SizingFixedFit = 1 << 13
const TableFlags_SizingFixedSame = 2 << 13
const TableFlags_SizingStretchProp = 3 << 13
const TableFlags_SizingStretchSame = 4 << 13
const TableFlags_NoHostExtendX = 1 << 16
const TableFlags_NoHostExtendY = 1 << 17
const TableFlags_NoKeepColumnsVisible = 1 << 18
const TableFlags_PreciseWidths = 1 << 19
const TableFlags_NoClip = 1 << 20
const TableFlags_PadOuterX = 1 << 21
const TableFlags_NoPadOuterX = 1 << 22
const TableFlags_NoPadInnerX = 1 << 23
const TableFlags_ScrollX = 1 << 24
const TableFlags_ScrollY = 1 << 25
const TableFlags_SortMulti = 1 << 26
const TableFlags_SortTristate = 1 << 27
const TableFlags_HighlightHoveredColumn = 1 << 28
const TableFlags_SizingMask_ = TableFlags_SizingFixedFit | TableFlags_SizingFixedSame | TableFlags_SizingStretchProp | TableFlags_SizingStretchSame
const TableColumnFlags_None = 0
const TableColumnFlags_Disabled = 1 << 0
const TableColumnFlags_DefaultHide = 1 << 1
const TableColumnFlags_DefaultSort = 1 << 2
const TableColumnFlags_WidthStretch = 1 << 3
const TableColumnFlags_WidthFixed = 1 << 4
const TableColumnFlags_NoResize = 1 << 5
const TableColumnFlags_NoReorder = 1 << 6
const TableColumnFlags_NoHide = 1 << 7
const TableColumnFlags_NoClip = 1 << 8
const TableColumnFlags_NoSort = 1 << 9
const TableColumnFlags_NoSortAscending = 1 << 10
const TableColumnFlags_NoSortDescending = 1 << 11
const TableColumnFlags_NoHeaderLabel = 1 << 12
const TableColumnFlags_NoHeaderWidth = 1 << 13
const TableColumnFlags_PreferSortAscending = 1 << 14
const TableColumnFlags_PreferSortDescending = 1 << 15
const TableColumnFlags_IndentEnable = 1 << 16
const TableColumnFlags_IndentDisable = 1 << 17
const TableColumnFlags_AngledHeader = 1 << 18
const TableColumnFlags_IsEnabled = 1 << 24
const TableColumnFlags_IsVisible = 1 << 25
const TableColumnFlags_IsSorted = 1 << 26
const TableColumnFlags_IsHovered = 1 << 27
const TableColumnFlags_WidthMask_ = TableColumnFlags_WidthStretch | TableColumnFlags_WidthFixed
const TableColumnFlags_IndentMask_ = TableColumnFlags_IndentEnable | TableColumnFlags_IndentDisable
const TableColumnFlags_StatusMask_ = TableColumnFlags_IsEnabled | TableColumnFlags_IsVisible | TableColumnFlags_IsSorted | TableColumnFlags_IsHovered
const TableColumnFlags_NoDirectResize_ = 1 << 30
const TableRowFlags_None = 0
const TableRowFlags_Headers = 1 << 0
const TableBgTarget_None = 0
const TableBgTarget_RowBg0 = 1
const TableBgTarget_RowBg1 = 2
const TableBgTarget_CellBg = 3
const MultiSelectFlags_None = 0
const MultiSelectFlags_SingleSelect = 1 << 0
const MultiSelectFlags_NoSelectAll = 1 << 1
const MultiSelectFlags_NoRangeSelect = 1 << 2
const MultiSelectFlags_NoAutoSelect = 1 << 3
const MultiSelectFlags_NoAutoClear = 1 << 4
const MultiSelectFlags_NoAutoClearOnReselect = 1 << 5
const MultiSelectFlags_BoxSelect1d = 1 << 6
const MultiSelectFlags_BoxSelect2d = 1 << 7
const MultiSelectFlags_BoxSelectNoScroll = 1 << 8
const MultiSelectFlags_ClearOnEscape = 1 << 9
const MultiSelectFlags_ClearOnClickVoid = 1 << 10
const MultiSelectFlags_ScopeWindow = 1 << 11
const MultiSelectFlags_ScopeRect = 1 << 12
const MultiSelectFlags_SelectOnClick = 1 << 13
const MultiSelectFlags_SelectOnClickRelease = 1 << 14
const MultiSelectFlags_NavWrapX = 1 << 16
const SelectionRequestType_None = 0
const SelectionRequestType_SetAll = 0
const SelectionRequestType_SetRange = 1
const ImDrawFlags_None = 0
const ImDrawFlags_Closed = 1 << 0
const ImDrawFlags_RoundCornersTopLeft = 1 << 4
const ImDrawFlags_RoundCornersTopRight = 1 << 5
const ImDrawFlags_RoundCornersBottomLeft = 1 << 6
const ImDrawFlags_RoundCornersBottomRight = 1 << 7
const ImDrawFlags_RoundCornersNone = 1 << 8
const ImDrawFlags_RoundCornersTop = ImDrawFlags_RoundCornersTopLeft | ImDrawFlags_RoundCornersTopRight
const ImDrawFlags_RoundCornersBottom = ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersBottomRight
const ImDrawFlags_RoundCornersLeft = ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersTopLeft
const ImDrawFlags_RoundCornersRight = ImDrawFlags_RoundCornersBottomRight | ImDrawFlags_RoundCornersTopRight
const ImDrawFlags_RoundCornersAll = ImDrawFlags_RoundCornersTopLeft | ImDrawFlags_RoundCornersTopRight | ImDrawFlags_RoundCornersBottomLeft | ImDrawFlags_RoundCornersBottomRight
const ImDrawFlags_RoundCornersDefault_ = ImDrawFlags_RoundCornersAll
const ImDrawFlags_RoundCornersMask_ = ImDrawFlags_RoundCornersAll | ImDrawFlags_RoundCornersNone
const ImDrawListFlags_None = 0
const ImDrawListFlags_AntiAliasedLines = 1 << 0
const ImDrawListFlags_AntiAliasedLinesUseTex = 1 << 1
const ImDrawListFlags_AntiAliasedFill = 1 << 2
const ImDrawListFlags_AllowVtxOffset = 1 << 3
const ImFontAtlasFlags_None = 0
const ImFontAtlasFlags_NoPowerOfTwoHeight = 1 << 0
const ImFontAtlasFlags_NoMouseCursors = 1 << 1
const ImFontAtlasFlags_NoBakedLines = 1 << 2
const ViewportFlags_None = 0
const ViewportFlags_IsPlatformWindow = 1 << 0
const ViewportFlags_IsPlatformMonitor = 1 << 1
const ViewportFlags_OwnedByApp = 1 << 2
const ViewportFlags_NoDecoration = 1 << 3
const ViewportFlags_NoTaskBarIcon = 1 << 4
const ViewportFlags_NoFocusOnAppearing = 1 << 5
const ViewportFlags_NoFocusOnClick = 1 << 6
const ViewportFlags_NoInputs = 1 << 7
const ViewportFlags_NoRendererClear = 1 << 8
const ViewportFlags_NoAutoMerge = 1 << 9
const ViewportFlags_TopMost = 1 << 10
const ViewportFlags_CanHostOtherWindows = 1 << 11
const ViewportFlags_IsMinimized = 1 << 12
const ViewportFlags_IsFocused = 1 << 13
const DataType_String = DataType_COUNT + 1
const DataType_Pointer = 0
const DataType_ID = 1
const ItemFlags_Disabled = 1 << 10
const ItemFlags_ReadOnly = 1 << 11
const ItemFlags_MixedValue = 1 << 12
const ItemFlags_NoWindowHoverableCheck = 1 << 13
const ItemFlags_AllowOverlap = 1 << 14
const ItemFlags_Inputable = 1 << 20
const ItemFlags_HasSelectionUserData = 1 << 21
const ItemFlags_IsMultiSelect = 1 << 22
const ItemFlags_Default_ = ItemFlags_AutoClosePopups
const ItemStatusFlags_None = 0
const ItemStatusFlags_HoveredRect = 1 << 0
const ItemStatusFlags_HasDisplayRect = 1 << 1
const ItemStatusFlags_Edited = 1 << 2
const ItemStatusFlags_ToggledSelection = 1 << 3
const ItemStatusFlags_ToggledOpen = 1 << 4
const ItemStatusFlags_HasDeactivated = 1 << 5
const ItemStatusFlags_Deactivated = 1 << 6
const ItemStatusFlags_HoveredWindow = 1 << 7
const ItemStatusFlags_Visible = 1 << 8
const ItemStatusFlags_HasClipRect = 1 << 9
const ItemStatusFlags_HasShortcut = 1 << 10
const HoveredFlags_DelayMask_ = HoveredFlags_DelayNone | HoveredFlags_DelayShort | HoveredFlags_DelayNormal | HoveredFlags_NoSharedDelay
const HoveredFlags_AllowedMaskForIsWindowHovered = HoveredFlags_ChildWindows | HoveredFlags_RootWindow | HoveredFlags_AnyWindow | HoveredFlags_NoPopupHierarchy | HoveredFlags_DockHierarchy | HoveredFlags_AllowWhenBlockedByPopup | HoveredFlags_AllowWhenBlockedByActiveItem | HoveredFlags_ForTooltip | HoveredFlags_Stationary
const HoveredFlags_AllowedMaskForIsItemHovered = HoveredFlags_AllowWhenBlockedByPopup | HoveredFlags_AllowWhenBlockedByActiveItem | HoveredFlags_AllowWhenOverlapped | HoveredFlags_AllowWhenDisabled | HoveredFlags_NoNavOverride | HoveredFlags_ForTooltip | HoveredFlags_Stationary | HoveredFlags_DelayMask_
const InputTextFlags_Multiline = 1 << 26
const InputTextFlags_NoMarkEdited = 1 << 27
const InputTextFlags_MergedItem = 1 << 28
const InputTextFlags_LocalizeDecimalPoint = 1 << 29
const ButtonFlags_PressedOnClick = 1 << 4
const ButtonFlags_PressedOnClickRelease = 1 << 5
const ButtonFlags_PressedOnClickReleaseAnywhere = 1 << 6
const ButtonFlags_PressedOnRelease = 1 << 7
const ButtonFlags_PressedOnDoubleClick = 1 << 8
const ButtonFlags_PressedOnDragDropHold = 1 << 9
const ButtonFlags_Repeat = 1 << 10
const ButtonFlags_FlattenChildren = 1 << 11
const ButtonFlags_AllowOverlap = 1 << 12
const ButtonFlags_DontClosePopups = 1 << 13
const ButtonFlags_AlignTextBaseLine = 1 << 15
const ButtonFlags_NoKeyModifiers = 1 << 16
const ButtonFlags_NoHoldingActiveId = 1 << 17
const ButtonFlags_NoNavFocus = 1 << 18
const ButtonFlags_NoHoveredOnFocus = 1 << 19
const ButtonFlags_NoSetKeyOwner = 1 << 20
const ButtonFlags_NoTestKeyOwner = 1 << 21
const ButtonFlags_PressedOnMask_ = ButtonFlags_PressedOnClick | ButtonFlags_PressedOnClickRelease | ButtonFlags_PressedOnClickReleaseAnywhere | ButtonFlags_PressedOnRelease | ButtonFlags_PressedOnDoubleClick | ButtonFlags_PressedOnDragDropHold
const ButtonFlags_PressedOnDefault_ = ButtonFlags_PressedOnClickRelease
const ComboFlags_CustomPreview = 1 << 20
const SliderFlags_Vertical = 1 << 20
const SliderFlags_ReadOnly = 1 << 21
const SelectableFlags_NoHoldingActiveID = 1 << 20
const SelectableFlags_SelectOnNav = 1 << 21
const SelectableFlags_SelectOnClick = 1 << 22
const SelectableFlags_SelectOnRelease = 1 << 23
const SelectableFlags_SpanAvailWidth = 1 << 24
const SelectableFlags_SetNavIdOnHover = 1 << 25
const SelectableFlags_NoPadWithHalfSpacing = 1 << 26
const SelectableFlags_NoSetKeyOwner = 1 << 27
const TreeNodeFlags_ClipLabelForTrailingButton = 1 << 28
const TreeNodeFlags_UpsideDownArrow = 1 << 29
const TreeNodeFlags_OpenOnMask_ = TreeNodeFlags_OpenOnDoubleClick | TreeNodeFlags_OpenOnArrow
const SeparatorFlags_None = 0
const SeparatorFlags_Horizontal = 1 << 0
const SeparatorFlags_Vertical = 1 << 1
const SeparatorFlags_SpanAllColumns = 1 << 2
const FocusRequestFlags_None = 0
const FocusRequestFlags_RestoreFocusedChild = 1 << 0
const FocusRequestFlags_UnlessBelowModal = 1 << 1
const TextFlags_None = 0
const TextFlags_NoWidthForLargeClippedText = 1 << 0
const TooltipFlags_None = 0
const TooltipFlags_OverridePrevious = 1 << 1
const LayoutType_Horizontal = 0
const LayoutType_Vertical = 1
const LogType_None = 0
const LogType_TTY = 0
const LogType_File = 1
const LogType_Buffer = 2
const LogType_Clipboard = 3
const Axis_None = -1
const Axis_X = 0
const Axis_Y = 1
const PlotType_Lines = 0
const PlotType_Histogram = 1
const WindowRefreshFlags_None = 0
const WindowRefreshFlags_TryToAvoidRefresh = 1 << 0
const WindowRefreshFlags_RefreshOnHover = 1 << 1
const WindowRefreshFlags_RefreshOnFocus = 1 << 2
const NextWindowDataFlags_None = 0
const NextWindowDataFlags_HasPos = 1 << 0
const NextWindowDataFlags_HasSize = 1 << 1
const NextWindowDataFlags_HasContentSize = 1 << 2
const NextWindowDataFlags_HasCollapsed = 1 << 3
const NextWindowDataFlags_HasSizeConstraint = 1 << 4
const NextWindowDataFlags_HasFocus = 1 << 5
const NextWindowDataFlags_HasBgAlpha = 1 << 6
const NextWindowDataFlags_HasScroll = 1 << 7
const NextWindowDataFlags_HasChildFlags = 1 << 8
const NextWindowDataFlags_HasRefreshPolicy = 1 << 9
const NextWindowDataFlags_HasViewport = 1 << 10
const NextWindowDataFlags_HasDock = 1 << 11
const NextWindowDataFlags_HasWindowClass = 1 << 12
const NextItemDataFlags_None = 0
const NextItemDataFlags_HasWidth = 1 << 0
const NextItemDataFlags_HasOpen = 1 << 1
const NextItemDataFlags_HasShortcut = 1 << 2
const NextItemDataFlags_HasRefVal = 1 << 3
const NextItemDataFlags_HasStorageID = 1 << 4
const PopupPositionPolicy_Default = 0
const PopupPositionPolicy_ComboBox = 1
const PopupPositionPolicy_Tooltip = 2
const InputEventType_None = 0
const InputEventType_MousePos = 0
const InputEventType_MouseWheel = 1
const InputEventType_MouseButton = 2
const InputEventType_MouseViewport = 3
const InputEventType_Key = 4
const InputEventType_Text = 5
const InputEventType_Focus = 6
const InputEventType_COUNT = 7
const InputSource_None = 0
const InputSource_Mouse = 0
const InputSource_Keyboard = 1
const InputSource_Gamepad = 2
const InputSource_COUNT = 3
const InputFlags_RepeatRateDefault = 1 << 1
const InputFlags_RepeatRateNavMove = 1 << 2
const InputFlags_RepeatRateNavTweak = 1 << 3
const InputFlags_RepeatUntilRelease = 1 << 4
const InputFlags_RepeatUntilKeyModsChange = 1 << 5
const InputFlags_RepeatUntilKeyModsChangeFromNone = 1 << 6
const InputFlags_RepeatUntilOtherKeyPress = 1 << 7
const InputFlags_LockThisFrame = 1 << 20
const InputFlags_LockUntilRelease = 1 << 21
const InputFlags_CondHovered = 1 << 22
const InputFlags_CondActive = 1 << 23
const InputFlags_CondDefault_ = InputFlags_CondHovered | InputFlags_CondActive
const InputFlags_RepeatRateMask_ = InputFlags_RepeatRateDefault | InputFlags_RepeatRateNavMove | InputFlags_RepeatRateNavTweak
const InputFlags_RepeatUntilMask_ = InputFlags_RepeatUntilRelease | InputFlags_RepeatUntilKeyModsChange | InputFlags_RepeatUntilKeyModsChangeFromNone | InputFlags_RepeatUntilOtherKeyPress
const InputFlags_RepeatMask_ = InputFlags_Repeat | InputFlags_RepeatRateMask_ | InputFlags_RepeatUntilMask_
const InputFlags_CondMask_ = InputFlags_CondHovered | InputFlags_CondActive
const InputFlags_RouteTypeMask_ = InputFlags_RouteActive | InputFlags_RouteFocused | InputFlags_RouteGlobal | InputFlags_RouteAlways
const InputFlags_RouteOptionsMask_ = InputFlags_RouteOverFocused | InputFlags_RouteOverActive | InputFlags_RouteUnlessBgFocused | InputFlags_RouteFromRootWindow
const InputFlags_SupportedByIsKeyPressed = InputFlags_RepeatMask_
const InputFlags_SupportedByIsMouseClicked = InputFlags_Repeat
const InputFlags_SupportedByShortcut = InputFlags_RepeatMask_ | InputFlags_RouteTypeMask_ | InputFlags_RouteOptionsMask_
const InputFlags_SupportedBySetNextItemShortcut = InputFlags_RepeatMask_ | InputFlags_RouteTypeMask_ | InputFlags_RouteOptionsMask_ | InputFlags_Tooltip
const InputFlags_SupportedBySetKeyOwner = InputFlags_LockThisFrame | InputFlags_LockUntilRelease
const InputFlags_SupportedBySetItemKeyOwner = InputFlags_SupportedBySetKeyOwner | InputFlags_CondMask_
const ActivateFlags_None = 0
const ActivateFlags_PreferInput = 1 << 0
const ActivateFlags_PreferTweak = 1 << 1
const ActivateFlags_TryToPreserveState = 1 << 2
const ActivateFlags_FromTabbing = 1 << 3
const ActivateFlags_FromShortcut = 1 << 4
const ScrollFlags_None = 0
const ScrollFlags_KeepVisibleEdgeX = 1 << 0
const ScrollFlags_KeepVisibleEdgeY = 1 << 1
const ScrollFlags_KeepVisibleCenterX = 1 << 2
const ScrollFlags_KeepVisibleCenterY = 1 << 3
const ScrollFlags_AlwaysCenterX = 1 << 4
const ScrollFlags_AlwaysCenterY = 1 << 5
const ScrollFlags_NoScrollParent = 1 << 6
const ScrollFlags_MaskX_ = ScrollFlags_KeepVisibleEdgeX | ScrollFlags_KeepVisibleCenterX | ScrollFlags_AlwaysCenterX
const ScrollFlags_MaskY_ = ScrollFlags_KeepVisibleEdgeY | ScrollFlags_KeepVisibleCenterY | ScrollFlags_AlwaysCenterY
const NavHighlightFlags_None = 0
const NavHighlightFlags_Compact = 1 << 1
const NavHighlightFlags_AlwaysDraw = 1 << 2
const NavHighlightFlags_NoRounding = 1 << 3
const NavMoveFlags_None = 0
const NavMoveFlags_LoopX = 1 << 0
const NavMoveFlags_LoopY = 1 << 1
const NavMoveFlags_WrapX = 1 << 2
const NavMoveFlags_WrapY = 1 << 3
const NavMoveFlags_WrapMask_ = NavMoveFlags_LoopX | NavMoveFlags_LoopY | NavMoveFlags_WrapX | NavMoveFlags_WrapY
const NavMoveFlags_AllowCurrentNavId = 1 << 4
const NavMoveFlags_AlsoScoreVisibleSet = 1 << 5
const NavMoveFlags_ScrollToEdgeY = 1 << 6
const NavMoveFlags_Forwarded = 1 << 7
const NavMoveFlags_DebugNoResult = 1 << 8
const NavMoveFlags_FocusApi = 1 << 9
const NavMoveFlags_IsTabbing = 1 << 10
const NavMoveFlags_IsPageMove = 1 << 11
const NavMoveFlags_Activate = 1 << 12
const NavMoveFlags_NoSelect = 1 << 13
const NavMoveFlags_NoSetNavHighlight = 1 << 14
const NavMoveFlags_NoClearActiveId = 1 << 15
const NavLayer_Main = 0
const NavLayer_Menu = 1
const NavLayer_COUNT = 0
const TypingSelectFlags_None = 0
const TypingSelectFlags_AllowBackspace = 1 << 0
const TypingSelectFlags_AllowSingleCharMode = 1 << 1
const OldColumnFlags_None = 0
const OldColumnFlags_NoBorder = 1 << 0
const OldColumnFlags_NoResize = 1 << 1
const OldColumnFlags_NoPreserveWidths = 1 << 2
const OldColumnFlags_NoForceWithinWindow = 1 << 3
const OldColumnFlags_GrowParentContentsSize = 1 << 4
const DockNodeFlags_DockSpace = 1 << 10
const DockNodeFlags_CentralNode = 1 << 11
const DockNodeFlags_NoTabBar = 1 << 12
const DockNodeFlags_HiddenTabBar = 1 << 13
const DockNodeFlags_NoWindowMenuButton = 1 << 14
const DockNodeFlags_NoCloseButton = 1 << 15
const DockNodeFlags_NoResizeX = 1 << 16
const DockNodeFlags_NoResizeY = 1 << 17
const DockNodeFlags_DockedWindowsInFocusRoute = 1 << 18
const DockNodeFlags_NoDockingSplitOther = 1 << 19
const DockNodeFlags_NoDockingOverMe = 1 << 20
const DockNodeFlags_NoDockingOverOther = 1 << 21
const DockNodeFlags_NoDockingOverEmpty = 1 << 22
const DockNodeFlags_NoDocking = DockNodeFlags_NoDockingOverMe | DockNodeFlags_NoDockingOverOther | DockNodeFlags_NoDockingOverEmpty | DockNodeFlags_NoDockingSplit | DockNodeFlags_NoDockingSplitOther
const DockNodeFlags_SharedFlagsInheritMask_ = ^0
const DockNodeFlags_NoResizeFlagsMask_ = DockNodeFlags_NoResize | DockNodeFlags_NoResizeX | DockNodeFlags_NoResizeY
const DockNodeFlags_LocalFlagsTransferMask_ = DockNodeFlags_NoDockingSplit | DockNodeFlags_NoResizeFlagsMask_ | DockNodeFlags_AutoHideTabBar | DockNodeFlags_CentralNode | DockNodeFlags_NoTabBar | DockNodeFlags_HiddenTabBar | DockNodeFlags_NoWindowMenuButton | DockNodeFlags_NoCloseButton
const DockNodeFlags_SavedFlagsMask_ = DockNodeFlags_NoResizeFlagsMask_ | DockNodeFlags_DockSpace | DockNodeFlags_CentralNode | DockNodeFlags_NoTabBar | DockNodeFlags_HiddenTabBar | DockNodeFlags_NoWindowMenuButton | DockNodeFlags_NoCloseButton
const DataAuthority_Auto = 0
const DataAuthority_DockNode = 1
const DataAuthority_Window = 2
const DockNodeState_Unknown = 0
const DockNodeState_HostWindowHiddenBecauseSingleWindow = 1
const DockNodeState_HostWindowHiddenBecauseWindowsAreResizing = 2
const DockNodeState_HostWindowVisible = 3
const WindowDockStyleCol_Text = 0
const WindowDockStyleCol_TabHovered = 1
const WindowDockStyleCol_TabFocused = 2
const WindowDockStyleCol_TabSelected = 3
const WindowDockStyleCol_TabSelectedOverline = 4
const WindowDockStyleCol_TabDimmed = 5
const WindowDockStyleCol_TabDimmedSelected = 6
const WindowDockStyleCol_TabDimmedSelectedOverline = 7
const WindowDockStyleCol_COUNT = 8
const LocKey_VersionStr = 0
const LocKey_TableSizeOne = 1
const LocKey_TableSizeAllFit = 2
const LocKey_TableSizeAllDefault = 3
const LocKey_TableResetOrder = 4
const LocKey_WindowingMainMenuBar = 5
const LocKey_WindowingPopup = 6
const LocKey_WindowingUntitled = 7
const LocKey_OpenLink_s = 8
const LocKey_CopyLink = 9
const LocKey_DockingHideTabBar = 10
const LocKey_DockingHoldShiftToDock = 11
const LocKey_DockingDragToUndockOrMoveNode = 12
const LocKey_COUNT = 13
const DebugLogFlags_None = 0
const DebugLogFlags_EventActiveId = 1 << 0
const DebugLogFlags_EventFocus = 1 << 1
const DebugLogFlags_EventPopup = 1 << 2
const DebugLogFlags_EventNav = 1 << 3
const DebugLogFlags_EventClipper = 1 << 4
const DebugLogFlags_EventSelection = 1 << 5
const DebugLogFlags_EventIO = 1 << 6
const DebugLogFlags_EventInputRouting = 1 << 7
const DebugLogFlags_EventDocking = 1 << 8
const DebugLogFlags_EventViewport = 1 << 9
const DebugLogFlags_EventMask_ = DebugLogFlags_EventActiveId | DebugLogFlags_EventFocus | DebugLogFlags_EventPopup | DebugLogFlags_EventNav | DebugLogFlags_EventClipper | DebugLogFlags_EventSelection | DebugLogFlags_EventIO | DebugLogFlags_EventInputRouting | DebugLogFlags_EventDocking | DebugLogFlags_EventViewport
const DebugLogFlags_OutputToTTY = 1 << 20
const DebugLogFlags_OutputToTestEngine = 1 << 21
const TabBarFlags_DockNode = 1 << 20
const TabBarFlags_IsFocused = 1 << 21
const TabBarFlags_SaveSettings = 1 << 22
const TabItemFlags_SectionMask_ = TabItemFlags_Leading | TabItemFlags_Trailing
const TabItemFlags_NoCloseButton = 1 << 20
const TabItemFlags_Button = 1 << 21
const TabItemFlags_Unsorted = 1 << 22